### ISSUE TITLE
Identificare le esigenze degli utenti attraverso HU

### ISSUE THREAD

**Issue by MatteoImbrosciano** [MatteoImbrosciano/Medication-Management#22]
Identificare le esigenze degli utenti tramite HU prima di iniziare lo sviluppo. Una volta identificati, implementare test unitari che riflettono queste esigenze utilizzando la metodologia Test-Driven Development (TDD) per garantire il corretto funzionamento del sistema, relativo al problema #4, #5

**Comment by JJ** [comment]
Ciò non è corretto, Matteo. La storia di utente parla soltanto di processare le recette, ed devi sviluppare la logica di negozio necessaria per ciò. Non metti tutto il codice per questo issue qui, che purtroppo non è una descrizione di un problema, ma di uno scopo, una roba a fare.

**Comment by JJ** [comment]
Non è ancora un problema, è sempre un compito. Issue devono essere problemi, che si resolvono via codice e si provano via tests.
