### ISSUE TITLE
Come si ottengono le assegnazioni?

### ISSUE THREAD

**Issue by MatteoImbrosciano** [MatteoImbrosciano/Medication-Management#23]
Come descritto nella #4, si dice che è necessario scegliere le assegnazioni per formare l'orario. Queste assegnazioni figurano in un file che le contiene. Come parte del [Milestone 1] dobbiamo trovare il modo di leggere un file in cui figurano le assegnazioni. Come possiamo fare questo?

**Comment by JJ** [comment]
Gestione di cosa? Devi sollevare un problema che ha un rapporto con la storia di utente #5. Se non si fa così, è impossibile risolvere le problememe del utente.

**Comment by JJ** [comment]
Soluzione di cosa? Se non si dice quale é il problema, è impossibile trovare la soluzione (e scrivere il test per probarlo)
Come ho detto, sviluppare e più di un 50% riflessione, e il resto codice. Se non ne fai correttamente, è impossibile trovare nessuna soluzione. Perlopiù, devi credere che fare così e meglio e più efficiente che semplicemente scrivere codice (oppure chiedere CoPilot di farlo da solo)

**Comment by MatteoImbrosciano** [comment]
l'ho aggiornato, @JJ  puoi revisionare

**Comment by JJ** [comment]
Il titolo non è aggiornato, e ancora parla di fare questo o quello. Un issue è *sempre* un problema, e dividere tutto ciò che serve per andare fino al prossimo milestone è quello que si deve fare qui. Non é semplicemente riscrivere questo issue, ma pensare su tutti i problemi che stanno presenti sulla storia di utente.

**Comment by MatteoImbrosciano** [comment]
va bene questo problema come problema? @JJ

**Comment by JJ** [comment]
Se è soltanto 1 issue, molto probabile che no, Matteo.

**Comment by MatteoImbrosciano** [comment]
sono 4 issue

**Comment by JJ** [comment]
E perlopiù non hai collegato la storia di utente. Lo svilupo del codice deve andare sempre sull indirizzo SU → issue → codice (ed in dietro)

**Comment by JJ** [comment]
> Sviluppare il codice funzionale minimo necessario affinché possa visualizzare i ticket

Ti pare che ciò è la descrizione di un problema oppure un compito?

Se non sai fare la descrizione dello problema dell'utente, è impossibile risolverne.

**Comment by MatteoImbrosciano** [comment]
La storia utente vuole visualizzare e inserire manualmente i ticket

**Comment by JJ** [comment]
Quindi la storia utente non è neanche valida. Una storia utente è anche un problema, non una voglia di fare cosa. Non capisco perchè è andata avanti cosí.

**Comment by MatteoImbrosciano** [comment]
Non ho capito. La mia storia utente non è valida?

**Comment by MatteoImbrosciano** [comment]
Potrebbe darmi una mano a capire che è quasi un mese che lavoro su questo obiettivo ogni giorno. Non so più che devo fare

**Comment by JJ** [comment]
Che laboriamo, Matteo. Tutti i due, vuol dì.

**Comment by MatteoImbrosciano** [comment]
devo modificare la storia utente?

**Comment by JJ** [comment]
Fammi vedere, Matteo. Dammi un po' di tempo.

**Comment by MatteoImbrosciano** [comment]
ok grazie, scusi per il disturbo
