### ISSUE TITLE
Lenguaje de programación a usar en el proyecto

### ISSUE THREAD

**Issue by wickeet** [MatteoImbrosciano/Medication-Management#8]
Hola @MatteoImbrosciano, para trabajar sobre el repositorio antes hay que ponerse de acuerdo sobre qué lenguaje de programación vamos a usar en él. Había pensado en usar Python, ya que es un lenguaje en el que los dos tenemos experiencia y es un lenguaje bastante versátil. ¿Qué opinas?

**Comment by MatteoImbrosciano** [comment]
Hola Karim, si Python está bien para mí
